In [ ]:
import numpy as np
from numpy import random
from numpy import linalg
import matplotlib.pyplot as plt

In [2]:
np.random.seed(42)

In [8]:
MyData = np.random.rand(100)

In [9]:
MyData.shape


(100,)

In [18]:
MyData.reshape((20,5))
data= MyData.reshape((20,5))


In [23]:
data

array([[0.70723863, 0.15253904, 0.57628836, 0.60671505, 0.42413067],
       [0.73644424, 0.93436701, 0.92556851, 0.45083937, 0.11323805],
       [0.9848412 , 0.83889809, 0.12466268, 0.92084188, 0.86989636],
       [0.51883806, 0.59127544, 0.3990027 , 0.05476164, 0.33519724],
       [0.80285345, 0.00463202, 0.33349917, 0.39816869, 0.5373956 ],
       [0.91985562, 0.34634599, 0.3469532 , 0.73750125, 0.45221794],
       [0.22460482, 0.45243952, 0.14085702, 0.17638699, 0.49836777],
       [0.41892545, 0.9148459 , 0.3623939 , 0.58058835, 0.63226429],
       [0.01309446, 0.66353737, 0.17803597, 0.96107032, 0.14866273],
       [0.41462412, 0.08534967, 0.99687425, 0.50219501, 0.59538502],
       [0.06707648, 0.74996047, 0.20990559, 0.89805429, 0.20513964],
       [0.19068772, 0.03654967, 0.47206695, 0.56484113, 0.06570864],
       [0.77552762, 0.45328883, 0.52439027, 0.44076275, 0.40076306],
       [0.55964033, 0.15524025, 0.18192813, 0.86178562, 0.94611546],
       [0.37330932, 0.27074467, 0.

In [38]:
print("sum  of feature 1 : " , np.sum(data ,  axis=0))
print("min  of feature 1 : " , np.min(data ,  axis=0))
print("max  of feature 1 : " , np.max(data ,  axis=0))
print("mean  of feature 1 : " , np.mean(data ,  axis=0))
print("median  of feature 1 : " , np.median(data ,  axis=0))
print("std  of feature 1 : " , np.std(data ,  axis=0))
print("var  of feature 1 : " , np.var(data ,  axis=0))
Q1 = np.quantile(data,0.25,axis=0) 
Q2 = np.quantile(data,axis=0,q=0.5) 
Q3 = np.quantile(data,axis=0,q=0.27) 
print(Q1)
print(Q2)
print(Q3)
IQR = Q3 - Q1
print(IQR)


sum  of feature 1 :  [9.20058479 9.83946923 9.0597992  9.20407793 8.26852293]
min  of feature 1 :  [0.01309446 0.00463202 0.01971054 0.01300192 0.02538636]
max  of feature 1 :  [0.9848412  0.93436701 0.99687425 0.96107032 0.94611546]
mean  of feature 1 :  [0.46002924 0.49197346 0.45298996 0.4602039  0.41342615]
median  of feature 1 :  [0.41677479 0.52228214 0.3806983  0.44580106 0.41244687]
std  of feature 1 :  [0.29206583 0.29941876 0.28648418 0.30347941 0.27074711]
var  of feature 1 :  [0.08530245 0.0896516  0.08207319 0.09209975 0.073304  ]
[0.20141015 0.24186857 0.20291123 0.15831739 0.19102041]
[0.41677479 0.52228214 0.3806983  0.44580106 0.41244687]
[0.20753496 0.27365707 0.21358163 0.20509054 0.20732787]
[0.00612481 0.0317885  0.0106704  0.04677315 0.01630746]


In [ ]:
feature_1_Vector= data[ 0: , 1]


In [49]:
feature_1_Vector

array([0.15253904, 0.93436701, 0.83889809, 0.59127544, 0.00463202,
       0.34634599, 0.45243952, 0.9148459 , 0.66353737, 0.08534967,
       0.74996047, 0.03654967, 0.45328883, 0.15524025, 0.27074467,
       0.71597223, 0.67189274, 0.65274611, 0.85569647, 0.29314773])

In [56]:
Vector_1_l1 = np.linalg.norm(feature_1_Vector , 1)
Vector_1_l2 = np.linalg.norm(feature_1_Vector , 2)
Vector_1_inf = np.linalg.norm(feature_1_Vector , np.inf)

In [52]:
print(Vector_1_l1)


9.83946922527572


In [ ]:
print(Vector_1_l2)

2.575614420898047


In [57]:
print(Vector_1_inf)

0.9343670147690148


In [59]:
try:
    np.invert(data)
except:
    print("matrix not invertable")

matrix not invertable
