# 🔢 NumPy Homework — Class Grades Analyzer

**Estimated time:** ~1 hour

**Goal:** apply array creation, broadcasting, boolean masking, `axis`-aware aggregation,
sorting, and array manipulation on one connected scenario.

You are analyzing grades for **5 students** across **6 subjects**. Work through the tasks in
order — later tasks build on earlier ones. Add your code in the empty cell under each task.

In [1]:
import numpy as np
np.random.seed(42)

## Task 1 — Create the data (5 min)

Create a 5×6 array called `grades` of random integers between 40 and 100 (inclusive of 40,
exclusive of 101), representing grades for 5 students across 6 subjects.

Also create an array `students = np.array(['Layla', 'Omar', 'Sara', 'Kareem', 'Nour'])` and
`subjects = np.array(['Math', 'Science', 'English', 'History', 'Art', 'PE'])`.

In [5]:
grades = np.random.uniform(40,100 , (5,6))
grades_ = np.round(grades,1)
print(grades_)



[[47.2 82.8 85.6 73.7 86.3 69.6]
 [71.4 65.7 41.5 46.5 41.9 78.2]
 [58.9 70.5 94.5 55.  64.6 85.3]
 [53.7 44.6 57.4 49.7 95.8 88.5]
 [78.  92.3 88.2 51.2 93.6 72.4]]


## Task 2 — Curve the grades (10 min)

Any grade **below 50** should get a **+5 curve**. Do this with boolean masking (no loops).
Print the updated `grades` array.

In [9]:
below_50 = np.where(grades_<50 )
print (grades_[below_50])
grades_[below_50] = grades_[below_50] +5
print (grades_[below_50])


[46.5 46.9 49.6]
[51.5 51.9 54.6]


## Task 3 — Row and column statistics (10 min)

Using the correct `axis`, compute:
- `student_avg`: each student's average grade across all subjects
- `subject_avg`: each subject's average grade across all students

Print both, labeled with the corresponding names from `students` / `subjects`.

In [12]:
print("Student_avrage : " , grades_.mean(axis=0))
print("subject_avrage : " , grades_.mean(axis=1))

Student_avrage :  [62.84 73.18 75.44 57.22 78.44 78.8 ]
subject_avrage :  [75.03333333 61.7        71.46666667 67.45       79.28333333]


## Task 4 — Who's on top? (10 min)

Using `np.argmax` / `np.argmin` (not manual comparison):
- Find the name of the **top-performing student** (highest `student_avg`).
- Find the name of the **hardest subject** (lowest `subject_avg`).

In [13]:
print("student Min average ",np.argmin(grades_, axis=0))

student Min average  [0 3 1 4 1 0]


## Task 5 — Pass/Fail matrix (10 min)

Using `np.where`, build a `status` array the same shape as `grades`, containing `'Pass'`
where the grade is ≥ 60 and `'Fail'` otherwise.

Then count how many total "Fail" entries exist in the whole matrix.

In [ ]:
# Your code here


## Task 6 — A new subject arrives (10 min)

A 6th subject, Music, is added. Generate a random grade for each of the 5 students
(same range as before) and add it as a **new column** to `grades` (use `np.append`,
`np.hstack`, or `np.column_stack` — your choice). Don't forget to also extend `subjects`
with `'Music'`.

Recompute `student_avg` with the new data.

In [ ]:
# Your code here


## Task 7 — Rank the students (10 min)

Use `np.argsort` on the updated `student_avg` to print students **from highest to lowest**
average grade (name + average, formatted nicely).

> Hint: `np.argsort` sorts ascending by default — you'll need to reverse it.

In [ ]:
# Your code here


## 🌟 Bonus — Normalize each student's grades (optional, ~10 min)

For each student (row), rescale their grades to a 0–1 range using min-max normalization:

`normalized = (grade - row_min) / (row_max - row_min)`

Do this **without a loop** — use `axis`-aware `.min(axis=...)` / `.max(axis=...)` together
with broadcasting (you'll need `keepdims=True` so the shapes line up for row-wise subtraction).

In [ ]:
# Your code here


---
### Submission checklist
- [ ] All 7 tasks run without errors, top to bottom
- [ ] Every array print is labeled (e.g. `print("Student averages:", ...)`) so it's readable
- [ ] No use of Python `for` loops for anything numpy could vectorize
- [ ] (Bonus) normalization attempted