In [2]:
import numpy as np

weekly_temperatures = np.random .uniform(low = 20 ,  high = 40 , size =(4,7))

In [4]:
print(weekly_temperatures)

[[24.58117954 24.0460436  36.87602523 27.2470984  24.30048603 25.4086564
  38.71156967]
 [34.94536853 38.44665339 29.499971   30.24564511 24.74676032 30.48102016
  39.85516909]
 [28.59980029 39.98516052 24.42398228 20.93003584 32.03573234 38.08281151
  21.00859882]
 [36.2984254  31.07151525 27.65017206 28.16653539 26.09303961 33.78382204
  27.76740968]]


In [11]:
weekly_temperatures= np.round(weekly_temperatures,1)

In [12]:
print(weekly_temperatures)


[[24.6 24.  36.9 27.2 24.3 25.4 38.7]
 [34.9 38.4 29.5 30.2 24.7 30.5 39.9]
 [28.6 40.  24.4 20.9 32.  38.1 21. ]
 [36.3 31.1 27.7 28.2 26.1 33.8 27.8]]


In [ ]:
weekdays = np.array(['saturday' ,  'sunday' , 'monday' , 'thurthday' ,'wednesday' ])